<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN""http://www.w3.org/TR/REC-html40/loose.dtd">
<!-- Generated by IDLdoc on Fri Jan  7 10:42:41 2005 -->
<HTML>
<HEAD>
<TITLE>IMaging Engine</TITLE>
</HEAD>
<LINK REL="SHORTCUT ICON" HREF="idldoc.ico">
<FRAMESET cols="20%,80%">
<FRAMESET rows="20%,50%,30%">
<FRAME src="all-dirs.html" name="dirslist_frame">
<FRAME src="all-files.html" name="dir_frame">
<FRAME src="blank.html" name="routine_frame">
</FRAMESET>
<FRAME src="overview.html" name="file_frame">
</FRAMESET>
<NOFRAMES>
<H2>Frame Alert</H2>
<P>
This document is designed to be viewed using the frames feature. If you see this message, you are using a non-frame-capable web client.
<BR>
Link to <A HREF="overview.html">Non-frame version.</A></NOFRAMES>
</HTML>
